
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author 30259508
 */
public class FlowerShop extends javax.swing.JFrame {
public  ArrayList<Flowers> buttonText=Flowers_DATA_Handler.getAllTheFlowers();
public int count =0;    
public  User theUser = new User();
Users_DATA_Handler myUsersHandler = new Users_DATA_Handler();
// INSTANTIATES TEH OBJECT
/**
     * Creates new form FlowerShop
     */
    public FlowerShop() {
        

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabMain = new javax.swing.JTabbedPane();
        tabEPOS = new javax.swing.JPanel();
        pnlEPOSQuantity = new javax.swing.JPanel();
        btnQuantity8 = new javax.swing.JButton();
        btnQuantity9 = new javax.swing.JButton();
        btnQuantity0 = new javax.swing.JButton();
        btnQuantity1 = new javax.swing.JButton();
        btnQuantity2 = new javax.swing.JButton();
        btnQuantity3 = new javax.swing.JButton();
        btnQuantity4 = new javax.swing.JButton();
        btnQuantity5 = new javax.swing.JButton();
        btnQuantity6 = new javax.swing.JButton();
        btnQuantity7 = new javax.swing.JButton();
        pnlEPOSButtons = new javax.swing.JPanel();
        btnProduct1 = new javax.swing.JButton();
        btnProduct2 = new javax.swing.JButton();
        btnProduct3 = new javax.swing.JButton();
        btnProduct4 = new javax.swing.JButton();
        btnProduct5 = new javax.swing.JButton();
        btnProduct6 = new javax.swing.JButton();
        btnProduct7 = new javax.swing.JButton();
        btnProduct8 = new javax.swing.JButton();
        btnProduct9 = new javax.swing.JButton();
        btnPurchase = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        pnlAddFlowers = new javax.swing.JPanel();
        pnlInternalAddFlowers = new javax.swing.JPanel();
        lblFlowerName = new javax.swing.JLabel();
        txtFlowerName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFlowerDescription = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFlowerPrice = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtFlowerScreen = new javax.swing.JTextField();
        btnAddFlower = new javax.swing.JButton();
        lblAddFlowerPanel = new javax.swing.JLabel();
        lblDone1 = new javax.swing.JLabel();
        pnlCreateUser = new javax.swing.JPanel();
        pnlInternalCreateUser = new javax.swing.JPanel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        lblPinNumber = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        btnCreateUser = new javax.swing.JButton();
        txtPassword = new javax.swing.JTextField();
        comboRole = new javax.swing.JComboBox<>();
        txtUserName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFirstName = new javax.swing.JTextField();
        lblCreateUsersTitle = new javax.swing.JLabel();
        lblDone2 = new javax.swing.JLabel();
        pnlClearStats = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        pnlUserStats = new javax.swing.JPanel();
        lblStatsUsername = new javax.swing.JLabel();
        lblStatsRealUsername = new javax.swing.JLabel();
        lblStatsFirstName = new javax.swing.JLabel();
        lblStatsRealFirstName = new javax.swing.JLabel();
        lblStatsLastName = new javax.swing.JLabel();
        lblStatsRealLastName = new javax.swing.JLabel();
        lblStatsRole = new javax.swing.JLabel();
        lblStatsRealRole = new javax.swing.JLabel();
        lblStatsSales = new javax.swing.JLabel();
        lblStatsRealSales = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlEPOSQuantity.setMaximumSize(new java.awt.Dimension(500, 500));
        pnlEPOSQuantity.setPreferredSize(new java.awt.Dimension(200, 200));

        btnQuantity8.setText("8");
        btnQuantity8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity8ActionPerformed(evt);
            }
        });

        btnQuantity9.setText("9");
        btnQuantity9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity9ActionPerformed(evt);
            }
        });

        btnQuantity0.setText("0");
        btnQuantity0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity0ActionPerformed(evt);
            }
        });

        btnQuantity1.setText("1");
        btnQuantity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity1ActionPerformed(evt);
            }
        });

        btnQuantity2.setText("2");
        btnQuantity2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity2ActionPerformed(evt);
            }
        });

        btnQuantity3.setText("3");
        btnQuantity3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity3ActionPerformed(evt);
            }
        });

        btnQuantity4.setText("4");
        btnQuantity4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity4ActionPerformed(evt);
            }
        });

        btnQuantity5.setText("5");
        btnQuantity5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity5ActionPerformed(evt);
            }
        });

        btnQuantity6.setText("6");
        btnQuantity6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity6ActionPerformed(evt);
            }
        });

        btnQuantity7.setText("7");
        btnQuantity7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantity7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEPOSQuantityLayout = new javax.swing.GroupLayout(pnlEPOSQuantity);
        pnlEPOSQuantity.setLayout(pnlEPOSQuantityLayout);
        pnlEPOSQuantityLayout.setHorizontalGroup(
            pnlEPOSQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEPOSQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnQuantity0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuantity5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuantity6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnQuantity8)
                .addGap(18, 18, 18)
                .addComponent(btnQuantity9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEPOSQuantityLayout.setVerticalGroup(
            pnlEPOSQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEPOSQuantityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEPOSQuantityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuantity0)
                    .addComponent(btnQuantity1)
                    .addComponent(btnQuantity2)
                    .addComponent(btnQuantity3)
                    .addComponent(btnQuantity4)
                    .addComponent(btnQuantity5)
                    .addComponent(btnQuantity6)
                    .addComponent(btnQuantity7)
                    .addComponent(btnQuantity8)
                    .addComponent(btnQuantity9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProduct1.setText(buttonText.get(count++).getFlowerName());
        btnProduct1.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct1.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct1ActionPerformed(evt);
            }
        });

        btnProduct2.setText(buttonText.get(count++).getFlowerName());
        btnProduct2.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct2.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct2ActionPerformed(evt);
            }
        });

        btnProduct3.setText(buttonText.get(count++).getFlowerName());
        btnProduct3.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct3.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct3ActionPerformed(evt);
            }
        });

        btnProduct4.setText(buttonText.get(count++).getFlowerName());
        btnProduct4.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct4.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct4ActionPerformed(evt);
            }
        });

        btnProduct5.setText(buttonText.get(count++).getFlowerName());
        btnProduct5.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct5.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct5ActionPerformed(evt);
            }
        });

        btnProduct6.setText(buttonText.get(count++).getFlowerName());
        btnProduct6.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct6.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct6ActionPerformed(evt);
            }
        });

        btnProduct7.setText(buttonText.get(count++).getFlowerName());
        btnProduct7.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct7.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct7ActionPerformed(evt);
            }
        });

        btnProduct8.setText(buttonText.get(count++).getFlowerName());
        btnProduct8.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct8.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct8ActionPerformed(evt);
            }
        });

        btnProduct9.setText(buttonText.get(count++).getFlowerName());
        btnProduct9.setMaximumSize(new java.awt.Dimension(120, 23));
        btnProduct9.setMinimumSize(new java.awt.Dimension(120, 23));
        btnProduct9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProduct9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEPOSButtonsLayout = new javax.swing.GroupLayout(pnlEPOSButtons);
        pnlEPOSButtons.setLayout(pnlEPOSButtonsLayout);
        pnlEPOSButtonsLayout.setHorizontalGroup(
            pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEPOSButtonsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEPOSButtonsLayout.createSequentialGroup()
                        .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEPOSButtonsLayout.createSequentialGroup()
                        .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlEPOSButtonsLayout.createSequentialGroup()
                        .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlEPOSButtonsLayout.setVerticalGroup(
            pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEPOSButtonsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct6, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(pnlEPOSButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProduct7, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct8, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProduct9, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        btnPurchase.setText("Purchase");
        btnPurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");

        lblTotal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTotal.setText("Total: £0.00");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout tabEPOSLayout = new javax.swing.GroupLayout(tabEPOS);
        tabEPOS.setLayout(tabEPOSLayout);
        tabEPOSLayout.setHorizontalGroup(
            tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEPOSLayout.createSequentialGroup()
                .addGroup(tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEPOSLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(pnlEPOSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tabEPOSLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlEPOSButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEPOSLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(202, 202, 202))
                    .addGroup(tabEPOSLayout.createSequentialGroup()
                        .addGroup(tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabEPOSLayout.createSequentialGroup()
                                .addComponent(btnPurchase)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnClear))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tabEPOSLayout.setVerticalGroup(
            tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEPOSLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabEPOSLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(tabEPOSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClear)
                            .addComponent(btnPurchase)))
                    .addGroup(tabEPOSLayout.createSequentialGroup()
                        .addComponent(pnlEPOSQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlEPOSButtons, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(lblTotal)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        tabMain.addTab("EPOS", tabEPOS);

        lblFlowerName.setText("Flower Name");

        jLabel2.setText("Flower Description");

        jLabel3.setText("Flower Price");

        jLabel1.setText("Flower Screen Position");

        btnAddFlower.setText("Add Flower");
        btnAddFlower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFlowerActionPerformed(evt);
            }
        });

        lblAddFlowerPanel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblAddFlowerPanel.setText("Add a Flower to the store database");

        javax.swing.GroupLayout pnlInternalAddFlowersLayout = new javax.swing.GroupLayout(pnlInternalAddFlowers);
        pnlInternalAddFlowers.setLayout(pnlInternalAddFlowersLayout);
        pnlInternalAddFlowersLayout.setHorizontalGroup(
            pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblAddFlowerPanel))
                        .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                            .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(lblFlowerName)
                                        .addComponent(jLabel3))
                                    .addGap(38, 38, 38))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInternalAddFlowersLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)))
                            .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFlowerPrice)
                                .addComponent(txtFlowerDescription)
                                .addComponent(txtFlowerScreen)
                                .addComponent(txtFlowerName))))
                    .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(btnAddFlower, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnlInternalAddFlowersLayout.setVerticalGroup(
            pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInternalAddFlowersLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblAddFlowerPanel)
                .addGap(18, 18, 18)
                .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFlowerName)
                    .addComponent(txtFlowerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFlowerDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFlowerPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pnlInternalAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFlowerScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnAddFlower)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        lblDone1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDone1.setText("DONE PLACEHOLDER");

        javax.swing.GroupLayout pnlAddFlowersLayout = new javax.swing.GroupLayout(pnlAddFlowers);
        pnlAddFlowers.setLayout(pnlAddFlowersLayout);
        pnlAddFlowersLayout.setHorizontalGroup(
            pnlAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFlowersLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(pnlInternalAddFlowers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addComponent(lblDone1)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        pnlAddFlowersLayout.setVerticalGroup(
            pnlAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddFlowersLayout.createSequentialGroup()
                .addGroup(pnlAddFlowersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAddFlowersLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(pnlInternalAddFlowers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAddFlowersLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(lblDone1)))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        tabMain.addTab("Add Flowers", pnlAddFlowers);

        lblFirstName.setText("First Name");

        lblLastName.setText("Last Name");

        lblUserName.setText("Username");

        lblPinNumber.setText("Pin Number");

        lblRole.setText("Role");

        btnCreateUser.setText("Create User");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        comboRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Manager" }));

        lblCreateUsersTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCreateUsersTitle.setText("Add a User to the database");

        javax.swing.GroupLayout pnlInternalCreateUserLayout = new javax.swing.GroupLayout(pnlInternalCreateUser);
        pnlInternalCreateUser.setLayout(pnlInternalCreateUserLayout);
        pnlInternalCreateUserLayout.setHorizontalGroup(
            pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInternalCreateUserLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlInternalCreateUserLayout.createSequentialGroup()
                        .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlInternalCreateUserLayout.createSequentialGroup()
                                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUserName)
                                    .addComponent(lblLastName)
                                    .addComponent(lblPinNumber)
                                    .addComponent(lblRole)
                                    .addComponent(btnCreateUser)
                                    .addComponent(lblFirstName))
                                .addGap(8, 8, 8)
                                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtPassword)
                                    .addGroup(pnlInternalCreateUserLayout.createSequentialGroup()
                                        .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 24, Short.MAX_VALUE))
                                    .addComponent(txtLastName)
                                    .addComponent(txtFirstName)))
                            .addComponent(lblCreateUsersTitle))
                        .addGap(1, 1, 1)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        pnlInternalCreateUserLayout.setVerticalGroup(
            pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInternalCreateUserLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblCreateUsersTitle)
                .addGap(18, 18, 18)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUserName)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPinNumber)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlInternalCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRole)
                    .addComponent(comboRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnCreateUser)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        lblDone2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDone2.setText("DONE PLACEHOLDER");

        javax.swing.GroupLayout pnlCreateUserLayout = new javax.swing.GroupLayout(pnlCreateUser);
        pnlCreateUser.setLayout(pnlCreateUserLayout);
        pnlCreateUserLayout.setHorizontalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(pnlInternalCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(lblDone2)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        pnlCreateUserLayout.setVerticalGroup(
            pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateUserLayout.createSequentialGroup()
                .addGroup(pnlCreateUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateUserLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(pnlInternalCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreateUserLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(lblDone2)))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        tabMain.addTab("Create User", pnlCreateUser);

        jButton1.setText("Clear All Sales Stats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlClearStatsLayout = new javax.swing.GroupLayout(pnlClearStats);
        pnlClearStats.setLayout(pnlClearStatsLayout);
        pnlClearStatsLayout.setHorizontalGroup(
            pnlClearStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClearStatsLayout.createSequentialGroup()
                .addGap(228, 228, 228)
                .addComponent(jButton1)
                .addContainerGap(411, Short.MAX_VALUE))
        );
        pnlClearStatsLayout.setVerticalGroup(
            pnlClearStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClearStatsLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jButton1)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        tabMain.addTab("Clear Stats", pnlClearStats);

        lblStatsUsername.setText("Username");

        lblStatsFirstName.setText("Firstname");

        lblStatsLastName.setText("Lastname");

        lblStatsRole.setText("Role");

        lblStatsSales.setText("Sales");

        lblStatsRealSales.setText("£"+lblTotal.getText().substring(8)
        );

        jLabel4.setText("Orders Taken");

        jLabel5.setText("0");

        javax.swing.GroupLayout pnlUserStatsLayout = new javax.swing.GroupLayout(pnlUserStats);
        pnlUserStats.setLayout(pnlUserStatsLayout);
        pnlUserStatsLayout.setHorizontalGroup(
            pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserStatsLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatsUsername)
                    .addComponent(lblStatsFirstName)
                    .addComponent(lblStatsLastName)
                    .addGroup(pnlUserStatsLayout.createSequentialGroup()
                        .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatsSales)
                            .addComponent(lblStatsRole)
                            .addComponent(jLabel4))
                        .addGap(41, 41, 41)
                        .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lblStatsRealSales)
                            .addComponent(lblStatsRealFirstName)
                            .addComponent(lblStatsRealLastName)
                            .addComponent(lblStatsRealUsername)
                            .addComponent(lblStatsRealRole))))
                .addContainerGap(560, Short.MAX_VALUE))
        );
        pnlUserStatsLayout.setVerticalGroup(
            pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUserStatsLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatsUsername)
                    .addComponent(lblStatsRealUsername))
                .addGap(33, 33, 33)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatsFirstName)
                    .addComponent(lblStatsRealFirstName))
                .addGap(18, 18, 18)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatsLastName)
                    .addComponent(lblStatsRealLastName))
                .addGap(28, 28, 28)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatsRole)
                    .addComponent(lblStatsRealRole))
                .addGap(26, 26, 26)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStatsSales)
                    .addComponent(lblStatsRealSales))
                .addGap(33, 33, 33)
                .addGroup(pnlUserStatsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        tabMain.addTab("User Stats", pnlUserStats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tabMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
            
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        checkTheLogin();
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        JOptionPane.showMessageDialog(null, "Are you sure you want to clear all the stats?");

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // ********************** //

        User myUser = new User ();

        myUser.setFirstName(txtFirstName.getText());
        myUser.setLastName(txtLastName.getText());
        myUser.setUserName(txtUserName.getText());
        myUser.setPinNumber(Integer.parseInt(txtPassword.getText()));
        myUser.setRole((String)comboRole.getSelectedItem());

        Users_DATA_Handler myHandler =new Users_DATA_Handler();
        myHandler.insertUser(myUser);

        JOptionPane.showMessageDialog(this, "User Created");

    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnAddFlowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFlowerActionPerformed

        Flowers myFlower = new Flowers ();

        myFlower.setFlowerName(txtFlowerName.getText());
        myFlower.setFlowerDescription(txtFlowerDescription.getText());
        myFlower.setFlowerPrice(Integer.parseInt(txtFlowerPrice.getText()));
        myFlower.setFlowerScreen(Integer.parseInt(txtFlowerScreen.getText()));

        Flowers_DATA_Handler myHandler =new Flowers_DATA_Handler();
        myHandler.insertFlowers(myFlower);

        JOptionPane.showMessageDialog(this, "Flower Added to Database");

    }//GEN-LAST:event_btnAddFlowerActionPerformed

    private void btnPurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseActionPerformed
if(!(jTextArea1.getText().equals("")))
{
        myUsersHandler.addOrder(theUser);
        jLabel5.setText(Integer.toString(theUser.getOrders()+1));
theUser.setOrders(theUser.getOrders()+1);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPurchaseActionPerformed

    private void btnProduct2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct2ActionPerformed

        jTextArea1.append(buttonText.get(1).getFlowerName()+"   "+buttonText.get(1).getFlowerPrice()+"\n");
         double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(1).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
                lblStatsRealSales.setText("£"+price);

    }//GEN-LAST:event_btnProduct2ActionPerformed

    private void btnProduct1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct1ActionPerformed
        jTextArea1.append(buttonText.get(0).getFlowerName()+"   "+buttonText.get(0).getFlowerPrice()+"\n");
        double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(0).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
                lblStatsRealSales.setText("£"+price);

    }//GEN-LAST:event_btnProduct1ActionPerformed

    private void btnQuantity7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity7ActionPerformed

    private void btnQuantity6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity6ActionPerformed

    private void btnQuantity5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity5ActionPerformed

    private void btnQuantity4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity4ActionPerformed

    private void btnQuantity3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity3ActionPerformed

    private void btnQuantity2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity2ActionPerformed

    private void btnQuantity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity1ActionPerformed

    private void btnQuantity0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity0ActionPerformed

    private void btnQuantity9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity9ActionPerformed

    private void btnQuantity8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantity8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantity8ActionPerformed

    private void btnProduct3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct3ActionPerformed
        jTextArea1.append(buttonText.get(2).getFlowerName()+"   "+buttonText.get(2).getFlowerPrice()+"\n");
         double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(2).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
        lblStatsRealSales.setText("£"+price);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct3ActionPerformed

    private void btnProduct4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct4ActionPerformed
        jTextArea1.append(buttonText.get(3).getFlowerName()+"   "+buttonText.get(3).getFlowerPrice()+"\n");
         double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(3).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
        lblStatsRealSales.setText("£"+price);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct4ActionPerformed

    private void btnProduct5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct5ActionPerformed
        jTextArea1.append(buttonText.get(4).getFlowerName()+"   "+buttonText.get(4).getFlowerPrice()+"\n");
         double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(4).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
        lblStatsRealSales.setText("£"+price);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct5ActionPerformed

    private void btnProduct6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct6ActionPerformed
        jTextArea1.append(buttonText.get(5).getFlowerName()+"   "+buttonText.get(5).getFlowerPrice()+"\n");
 double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(5).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
        lblStatsRealSales.setText("£"+price);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct6ActionPerformed

    private void btnProduct7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct7ActionPerformed
        jTextArea1.append(buttonText.get(6).getFlowerName()+"   "+buttonText.get(6).getFlowerPrice()+"\n");
 double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(6).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
                lblStatsRealSales.setText("£"+price);
    }//GEN-LAST:event_btnProduct7ActionPerformed

    private void btnProduct8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct8ActionPerformed
        jTextArea1.append(buttonText.get(7).getFlowerName()+"   "+buttonText.get(7).getFlowerPrice()+"\n");
 double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(7).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
                lblStatsRealSales.setText("£"+price);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct8ActionPerformed

    private void btnProduct9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProduct9ActionPerformed
        jTextArea1.append(buttonText.get(8).getFlowerName()+"   "+buttonText.get(8).getFlowerPrice()+"\n");
 double price=Double.parseDouble(lblTotal.getText().substring(8));
        price=price+buttonText.get(8).getFlowerPrice();
        lblTotal.setText("Total: £"+price);
        lblStatsRealSales.setText("£"+price);
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProduct9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FlowerShop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FlowerShop().setVisible(true);
                
            }
        });
    }
    


    public void checkTheLogin(){
    //programatically create the labels and texfields for the optionpane
    JLabel label_login = new JLabel("Username:");
    JTextField login = new JTextField();
    JLabel label_password = new JLabel("Password:");
    JPasswordField password = new JPasswordField();
 //-----------------------------------------------------
 // store these in an object array
 Object[] login_GUI_Elelemnts = { label_login, login, label_password, password };
 //-----------------------------------------------------
 int userInteraction = JOptionPane.showConfirmDialog(null, login_GUI_Elelemnts, "Login",
 JOptionPane.OK_CANCEL_OPTION,
 JOptionPane.PLAIN_MESSAGE);
// this integer variable 'userInteraction' will hold the result of
//the users interaction with the JOpttionPane
//we will then test the result against common returned values. OK OPtion , Cancel , Closed
//-----------------------------------------------------
 if (userInteraction == JOptionPane.OK_OPTION)
 {
 String user=login.getText().trim(); // user string that the user entered in the textfield
 String pass=new String(password.getPassword()); //pulls the password string from textfield
 Boolean entryGranted = false ;// setup boolean as false.
 //
 //
 //
 // !!!!!!!!!         You have to code this section       !!!!
 //
 //
 // 1) Setup a GLOBAL User variable  - Instantiate this user object then set the PIN Number and Username fields of the object using the setters 
 // 2) Instantiate a Users Data handler and call its method CheckUserIsValid - this returns a boolean
 //    if you receieve a TRUE then you have a valid user. 
 // 3) Once you have a valid user you can then use the method getValidUser of the DB Handler.- this returns a FULL VALID USER
 //
 
 

 theUser.setPinNumber(Integer.parseInt(pass));
 theUser.setUserName(user);
 
 System.out.println("The users data is now: " + theUser.toString());
 
 
 
 if (myUsersHandler.checkUserIsValid(theUser)){
     theUser = myUsersHandler.getValidUser(theUser);
     jLabel5.setText(Integer.toString(theUser.getOrders()));
     lblStatsRealUsername.setText(theUser.getUserName());
   lblStatsRealFirstName.setText(theUser.getFirstName());
   lblStatsRealLastName.setText(theUser.getLastName());
 lblStatsRealRole.setText(theUser.getRole()); 
 System.out.println("Equals: " + theUser.toString());
         }
 
         
// if (( user.toUpperCase().equals ("U")) && pass.toUpperCase().equals ("2")) // this line will change 
 // if users role is USER then....
 
  if (theUser.getRole().toUpperCase().equals("USER"))
    {
    JOptionPane.showMessageDialog(this, "Logged in as user\nCreate Users and Add Flowers options removed");
       //If an ordinary user logged in then remove the panel tabs that relate to administrators.
       
       //removes the user crud tab
       this.tabMain.remove(pnlCreateUser);
       this.tabMain.remove(pnlAddFlowers);
       this.tabMain.remove(pnlClearStats);
       entryGranted=true;
    }
 
 
 //if (( user.toUpperCase().equals ("M")) && pass.toUpperCase().equals ("1")) // this line will change
  // if users role is Manager then....
    
  if (theUser.getRole().toUpperCase().equals("MANAGER"))
  {
    JOptionPane.showMessageDialog(this, "Logged in as manager\nAccess granted to all areas");
    entryGranted=true;
    }
  
  
  
  
  
  
  
  
  
 if (!entryGranted) //entry denied
    {
    JOptionPane.showMessageDialog(this, "Go chase yourself - entry denied");
    userInteraction = JOptionPane.CANCEL_OPTION;
    }
 }
 
else
    {//user clicked on CANCEL or the X close button- we change the userInteraction to force execution of the CANCEL block of code
    userInteraction = JOptionPane.CANCEL_OPTION;
    }
 
 
 
 
 
 
 if ( (userInteraction == JOptionPane.CANCEL_OPTION) || (userInteraction == JOptionPane.CLOSED_OPTION) )
 // the cancel block of code - if user presses the X or CANCEL
    {
    //feedback to user and close the application as no suitable login credentials have been supplied.
    JOptionPane.showMessageDialog(this, "You have not supplied valid credentials\n the application will now terminate");
    System.exit(0);
    } 
 } 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddFlower;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnProduct1;
    private javax.swing.JButton btnProduct2;
    private javax.swing.JButton btnProduct3;
    private javax.swing.JButton btnProduct4;
    private javax.swing.JButton btnProduct5;
    private javax.swing.JButton btnProduct6;
    private javax.swing.JButton btnProduct7;
    private javax.swing.JButton btnProduct8;
    private javax.swing.JButton btnProduct9;
    private javax.swing.JButton btnPurchase;
    private javax.swing.JButton btnQuantity0;
    private javax.swing.JButton btnQuantity1;
    private javax.swing.JButton btnQuantity2;
    private javax.swing.JButton btnQuantity3;
    private javax.swing.JButton btnQuantity4;
    private javax.swing.JButton btnQuantity5;
    private javax.swing.JButton btnQuantity6;
    private javax.swing.JButton btnQuantity7;
    private javax.swing.JButton btnQuantity8;
    private javax.swing.JButton btnQuantity9;
    private javax.swing.JComboBox<String> comboRole;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblAddFlowerPanel;
    private javax.swing.JLabel lblCreateUsersTitle;
    private javax.swing.JLabel lblDone1;
    private javax.swing.JLabel lblDone2;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblFlowerName;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPinNumber;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblStatsFirstName;
    private javax.swing.JLabel lblStatsLastName;
    private javax.swing.JLabel lblStatsRealFirstName;
    private javax.swing.JLabel lblStatsRealLastName;
    private javax.swing.JLabel lblStatsRealRole;
    private javax.swing.JLabel lblStatsRealSales;
    private javax.swing.JLabel lblStatsRealUsername;
    private javax.swing.JLabel lblStatsRole;
    private javax.swing.JLabel lblStatsSales;
    private javax.swing.JLabel lblStatsUsername;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JPanel pnlAddFlowers;
    private javax.swing.JPanel pnlClearStats;
    private javax.swing.JPanel pnlCreateUser;
    private javax.swing.JPanel pnlEPOSButtons;
    private javax.swing.JPanel pnlEPOSQuantity;
    private javax.swing.JPanel pnlInternalAddFlowers;
    private javax.swing.JPanel pnlInternalCreateUser;
    private javax.swing.JPanel pnlUserStats;
    private javax.swing.JPanel tabEPOS;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFlowerDescription;
    private javax.swing.JTextField txtFlowerName;
    private javax.swing.JTextField txtFlowerPrice;
    private javax.swing.JTextField txtFlowerScreen;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
